import { Request, Response } from 'express';
import { FeeStructure } from '../../Model/feeModel';

// POST - Create a new Fee
export const createFee = async (req: Request, res: Response): Promise<void> => {
  try {
    const { feeName, feeAmount } = req.body as {
      feeName?: string;
      feeAmount?: number;
    };

    if (!feeName || feeAmount === undefined) {
      res.status(400).json({
        success: false,
        message: 'Required fields: feeName, feeAmount',
      });
      return;
    }

    // Do NOT accept feeId from client; it will be auto-generated by the model hook
    // Retry once on duplicate key in case of a rare race condition
    const attemptSave = async () => {
      const doc = new FeeStructure({ feeName, feeAmount });
      return await doc.save();
    };

    let savedFee;
    try {
      savedFee = await attemptSave();
    } catch (err: any) {
      if (err?.code === 11000) {
        // Retry once
        savedFee = await attemptSave();
      } else {
        throw err;
      }
    }

    res.status(201).json({
      success: true,
      message: 'Fee created successfully',
      data: savedFee,
    });
  } catch (error: any) {
    console.error('Error creating fee:', error);
    // Handle duplicate key errors gracefully
    if (error?.code === 11000) {
      res.status(409).json({
        success: false,
        message: 'A fee with this ID already exists. Please retry.',
      });
      return;
    }
    res.status(500).json({ success: false, message: error.message });
  }
};

// GET - Retrieve all Fees
export const getAllFees = async (
  _req: Request,
  res: Response
): Promise<void> => {
  try {
    const fees = await FeeStructure.find();
    res.status(200).json({ success: true, data: fees });
  } catch (error: any) {
    console.error('Error fetching fees:', error);
    res.status(500).json({ success: false, message: error.message });
  }
};
